# Use a lightweight Python image
FROM python:3.9-alpine

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Install required system dependencies
RUN apk add --no-cache git openssl graphicsmagick gcc musl-dev libffi-dev

# Set working directory inside the container
WORKDIR /home/dev/source


# Install dependencies
RUN pip install --no-cache-dir Flask

# Copy application files
COPY . .

# Expose Flask frontend port (default 5000)
EXPOSE 8000

# Start Flask frontend
CMD ["python", "app.py"]
